language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
before_script:
  - npm install -g npm@latest
script:
  - npm ci
  - npx jest --ci --passWithNoTests
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - npm ci
        - npx expo login -u jsbrain98 -p QrE9wyNjygt_4y2
        - npx expo publish --non-interactive
